### ISSUE TITLE
Can't complete scenario in Play with Jenkins

### ISSUE THREAD

**Issue by NicoForce** [frescoplaylab/jenkinsdemo#12]

**Comment by jpelles** [comment]
,

**Comment by NicoForce** [comment]
Somehow managed to finish successfully, so I guess I dont need the issue anymore.

**Comment by NicoForce** [comment]
Hey @Mrityunjay018 , 

Old me didn't know one had to put the description, screenshots, and expand on the solution when creating an issue, so I'm sorry for this one.

I can't recall what even the issue was, if you could elaborate some more, maybe I can lend a hand; although I recommend creating a new issue if that's the case.
